"""Add multi-dimensional weights to answers

Revision ID: bf79b3c1ef18
Revises: 76d987106dc4
Create Date: 2026-05-27 15:12:27.395432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf79b3c1ef18'
down_revision: Union[str, None] = '76d987106dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column as nullable
    op.add_column('answers', sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Step 2: Fill with default empty dict for existing rows
    op.execute("UPDATE answers SET weights = '{}'::jsonb WHERE weights IS NULL")

    # Step 3: Make it NOT NULL
    op.alter_column('answers', 'weights', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'weights')
    # ### end Alembic commands ###
